### ISSUE TITLE
wcd prefers local directory to bookmark

### ISSUE THREAD

**Issue by yellowtailfan** [bright-tools/wd#33]
The comments in wcd.bash imply that bookmarks will be used in preference to local directories, which is what I would like to happen. But I find the opposite is the case:
```
~$ wcd checkouts
~/checkouts$ cd ~/tmp
~/tmp$ wcd checkouts
/path/to/the/bookmark/checkouts$
```
This is the latest build from github on bash under Ubuntu Linux Bash for Windows 10.

Thanks for wd, it's great!

**Comment by bright-tools** [comment]
Thanks for pointing that out - should be fixed in the updated `wd.bash`, so just download & replace that file - no need to re-build the executable.  Let me know if you still run in to any problems.
